### ISSUE TITLE
updateSystemMetadata should be generalized to parent baseclient_2_0

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#10]
The MemberNodeClient_2_0.updateSystemMetadata() method could be generalized to the parent class baseclient_2_0 since CN API upadeSystemMetadata is the same method, thereby including it into the CoordinatingNodeClient_2_0 class through inheritance.

**Comment by rogerdahl** [comment]
Thanks Mark. Fixed in 4ada770b3c04cad97326fef27eff78d175ece1df
