### ISSUE TITLE
System metadata "submitter" attribute should mutable through updateSystemMetadata

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#11]
The "submitter" attribute in system metadata should be mutable through the updateSystemMetadata method call on the MN so that incorrect content on the MN can be modified to be consistent with what exists on the CN. This function is currently and quietly disabled through MemberNodeClient_2_0.updateSystemMetadata() on GMN v2.3.10.

**Comment by rogerdahl** [comment]
This comes under a more general need for clarifications on how `updateSystemMetadata()` should work in the API spec. Added it as an API spec issue. https://github.com/DataONEorg/api-documentation/issues/6
