### ISSUE TITLE
Implement the MNPackage API

### ISSUE THREAD

**Issue by csjx** [DataONEorg/d1_python#15]
Dave and Roger and I discussed the need for GMN to implement the `MNPackage.getPackage()` API endpoint to support the retrieval of Bagit zip files.  One implementation solution we discussed would be to store packages on the file system as pre-written bags to avoid heavy zip processing at request-time.  The downside of this is when objects participate in multiple packages, they get duplicated on disk.  

Note that the Metacat implementation of `getPackage()` is incomplete because it doesn't include the `SystemMetadata` document for each object in the bag, nor in the manifest.  This is an oversight, and having this information is critical to be able to pass Bagit bags from one system to the next as complete archives of the package.  Let's talk this through, and we'll fix the Metacat implementation as well.

@rogerdahl @datadavev - Let us know your thoughts on this.  Xiaoyan (@xli) and I could also work on the implementation depending on your current workload.

**Comment by datadavev** [comment]
Note that getPackage is implemented as of GMN 2.4.0. Implementation is at: 

* https://github.com/DataONEorg/d1_python/blob/master/gmn/src/d1_gmn/app/views/get_package.py
* https://github.com/DataONEorg/d1_python/blob/master/lib_common/src/d1_common/bagit.py

Need to evaluate wrt Chris' suggestions above.
