### ISSUE TITLE
System metadata update fails if dateSysMetadataModified not in XML

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#18]
Performing a system metadata update fails if a  dataSysMetadataModified element is not provided in the XML. A more user friendly approach would be for GMN to set this attribute if not supplied by the user as a side-effect of the update.

**Comment by rogerdahl** [comment]
The `dataSysMetadataModified` behavior is part of the optimistic locking that enforces complete read-modify-write cycles when handling sysmeta. Though it's only helpful if there's a possibility of multiple clients issuing concurrent updates to the same sysmeta, which is a use case that will be very rare in general, and non-existent in slendernode configs. Changing it would break compliance with the arch spec, so I guess I'll just leave as is. At least the `InvalidRequest` exception that is returned to the client includes a message saying how to fix it.
