### ISSUE TITLE
Aggregation URI difference between docs and implementation

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/d1_python#23]
I noticed that a resource map I generated with a call like 

```python
ore = createSimpleResourceMap(ore_pid, eml_pid, [data_pid])
```

used resource URIs of `https://cn-stage-2.test.dataone.org/cn/v2/resolve/dd0496da-fbf8-4925-9c57-8148b99402aa/aggregation`. The end of that URI, `/aggregation` was odd to me. The [API docs](http://jenkins-1.dataone.org/jenkins/job/API_Documentation_trunk/ws/api-documentation/build/html/design/DataPackage.html) make it look like aggregation URIs should end with `#aggregation`. I also noticed some instances in this package that use `Aggregation`.

Both forms, `#aggregation` and `/aggregation`, seem to index just fine but I'm curious if this is a problem or if it'd be good to stick with one form.

**Comment by rogerdahl** [comment]
Fixed in october last year. I guess I can get around to closing this issue now :) And thanks for the research, Bryce.
