### ISSUE TITLE
Support Adding a Path to an Object in an ORE

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/d1_python#26]
As per [this]() PR, it would be nice if we could add the path of a resource as we're adding it to the ResourceMap object. In my mind, the ideal way would be modifying `ResourceMap ::addResource(self, pid)` to `ResourceMap.addResource(self, pid, path)` where path is optional. It would also be pretty nice to be able to add a path to an existing object, something like `ResourceMap.addPath(self, pid, path)`.

As of August 19th, the vocabulary word is undecided, but it looks likely that it will be `prov:locatedAt`. Any thoughts on this @rogerdahl?

**Comment by mbjones** [comment]
This enhancement should also include support for the other data package changes proposed in https://github.com/DataONEorg/api-documentation/issues/5

**Comment by ThomasThelen** [comment]
This feature has been completed and merged
