### ISSUE TITLE
Issue New Release

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/d1_python#37]
This issue is used to track the progress of the next d1_python release. @datadavev this should be fine to review.

### Goals
The overall goals are to add support for adding file paths to the ORE.

### Issues Resolved

- [x] #26

### Version Number
If there was _only_ a bug fix, we could get away with a patch: 3.4.7 -> 3.4.8
Since there's also a new feature, I think (based on https://semver.org/) the new version should be 3.5.0
@rogerdahl might have stronger opinions on this.

**Comment by ThomasThelen** [comment]
This has been completed!

**Comment by amoeba** [comment]
Glad to see this land, thanks @ThomasThelen. Should we also update the `CHANGELOG.md` and issue a release+tag on GitHub to match the 3.5.0 version on PyPi?

**Comment by ThomasThelen** [comment]
@amoeba good catch! I put a topic in about this for the next dev call (historically I don't touch the versions).
