### ISSUE TITLE
Obsoleting Package Multiple Times Fails

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/d1_python#39]
When updating a package multiple times, a few exceptions are thrown from Metacat. I'm filing this in d1_python because other libraries that interface Metacat aren't running across this. The first obsoletion seems to work fine however, the second time it gets obsoleted things break down.

Exceptions: [Here](https://gist.github.com/ThomasThelen/aba806e4b69d3bef6c2a31ceb05f0fc9) Note that I added a few log statements in between
Code to Reproduce: [Here](https://gist.github.com/ThomasThelen/cc2a096267af7a70f5560a910e878f7e)

At face value, the first error is coming from a log statement that looks for the document's GUID, which doesn't exist for some reason. [The exception](https://github.com/NCEAS/metacat/blob/cd7e6a8947f327c78422d5da524cd0087df4dd1f/src/edu/ucsb/nceas/metacat/IdentifierManager.java#L954) isn't re-thrown and Metacat fails another time after. The null pointer exception is thrown when [this](https://github.com/NCEAS/metacat/blob/cd7e6a8947f327c78422d5da524cd0087df4dd1f/src/edu/ucsb/nceas/metacat/dataone/D1AuthHelper.java#L229) is called.

With some logging statements, I found that `sysmeta.getAuthoritativeMemberNode()` is returning `null`, which of course doesn't have the `equals` method. 

Taking at look at the system metadata that is generated from d1_python it looks like it's missing the `authoritativeMemberNode` field; I'm not sure if this is something that should be done on the client side, or if this is something that Metacat is supposed to insert.

**Comment by ThomasThelen** [comment]
The problem was on my end. I wasn't setting the `authoritativeMemberNode`. Closing :)

**Comment by amoeba** [comment]
I'm not so sure there isn't an error or bug _somewhere_ here.

The MDBC error about guids and docids is a bit suspicious as it's not something I usually see. And the (handled) NPE returning a "null" service failure is an application-layer bug in Metacat as it should at least do you the courtesy of saying it doesn't know why there was a ServiceFailure.

One thing I can note from your example Python code is the way you're doing the create and updates: You generate new sysmeta from scratch each time, whereas we usually grab an up-to-date copy of the sysmeta just before triggering the update call. See how it's done in R:

```r
> library(dataone)
> 
> node <- MNode("https://dev.nceas.ucsb.edu/knb/d1/mn/v2")
> 
> # Make a file to upload
> file_path <- tempfile()
> writeLines(LETTERS, file_path)
> 
> # Create sysmeta
> sysmeta <- new("SystemMetadata")
> sysmeta@identifier <- uuid::UUIDgenerate()
> sysmeta@size <- file.size(file_path)
> sysmeta@checksum <- digest::digest(file_path, "md5", file = TRUE)
> sysmeta@checksumAlgorithm <- "MD5"
> 
> # Initial upload
> cor <- createObject(node, sysmeta = sysmeta, file = file_path, pid = sysmeta@identifier)
> cor
[1] "1077eba6-48f3-4d53-8048-e6d70e8a2f8b"
> 
> # Obsolete once
> sysmeta <- getSystemMetadata(node, cor)
> sysmeta@identifier <- uuid::UUIDgenerate()
> 
> uor <- updateObject(node, sysmeta = sysmeta, file = file_path, pid = cor, newpid = sysmeta@identifier)
> uor
[1] "2d19534f-1146-4aa1-8b90-6e264a9ae852"
> 
> # Obsolete twice
> sysmeta <- getSystemMetadata(node, uor)
> sysmeta@identifier <- uuid::UUIDgenerate()
> sysmeta@obsoletes <- uor
> 
> uor <- updateObject(node, sysmeta = sysmeta, file = file_path, pid = uor, newpid = sysmeta@identifier)
> uor
[1] "c549a9f7-3b37-4b47-945e-a9b1da02af13"
```

Would it be easy enough for you to serialize out the sysmeta at each step so we can have a look?

**Comment by rogerdahl** [comment]
I think reading and modifying the old sysmeta for use in the new object in an `update()` is good if you want to ensure that you carry any modifications made to the old sysmeta forward to the new object. If you instead want to fully control the sysmeta for the new object, you'll want to generate it from scratch.

For `updateSystemMetadata()`, we want the operation to always be a complete read-modify-write cycle.

**Comment by amoeba** [comment]
Thanks @rogerdahl, that's all an aside to the problems here but it's interesting to hear nonetheless. Plenty of our tools don't work that way, just an FYI. Creating the sysmeta from scratch on every update is dangerous and very likely to make people sad. It does work well enough in isolated examples though.

Any thoughts on the other parts of the issue here? For example, @ThomasThelen writes:

> I wasn't setting the authoritativeMemberNode.

but this isn't necessary. Is there a chance `d1_python` is doing something odd or just exposing some bug in Metacat?

**Comment by ThomasThelen** [comment]
[Here's](https://gist.github.com/ThomasThelen/fceea6ac2915ba362fe806c83e23871e) a working example of where I set `authoratativeMemberNode` and get the expected behavior (the package obesoletes). Metacat hiccups when it tries to grab the `authoratativeMemberNode` [out of](https://github.com/NCEAS/metacat/blob/cd7e6a8947f327c78422d5da524cd0087df4dd1f/src/edu/ucsb/nceas/metacat/dataone/D1AuthHelper.java#L229) the System Metadata object. I was thinking that the _real_ issue was that I hadn't placed it there in the first place, which led me to manually placing it in the sysmeta.

My guess is that Metacat sets this value _somewhere_ and for some reason it's not. The docid and guid error might be playing a role, or shedding some light on part of the real issue. I'm going to peek around and see if I can see what's happening where it [should be getting set](https://github.com/NCEAS/metacat/blob/master/src/edu/ucsb/nceas/metacat/dataone/MNodeService.java#L698).
