### ISSUE TITLE
Update d1_python dependencies to work with python 3.8+

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/d1_python#76]
`d1_python` is currently limited to working with python 3.7 due to #40. There are several other updates that should be applied to avoid future deprecations blocking deployments.

Goal here is to ensure d1_python and particularly GMN can operate on python3.8 and later.

**Comment by MattF-NSIDC** [comment]
Can this issue (and #40) be closed now that #78 is merged?

**Comment by rogerdahl** [comment]
@MattF-NSIDC Yes -- good catch.
