### ISSUE TITLE
gmn/manage.py import proxied content not properly transferred

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#9]
Although the general import processed worked going from v2.0.7rc2 to v2.3.7, content that is proxies (i.e., using a vendor specific extension URL) did not transfer correctly, and when attempting to access object bytes, returns an IO File Not Found exception.

**Comment by rogerdahl** [comment]
Unfortunately, early GMN v2 versions do not expose the proxy state and network location of proxied objects, so the importer can't automatically create proxied objects. We'll need to handle these on a case by case basis by copying proxy URLs from source to destination database.
